__default__:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 1
  partition: debug
  cpus_per_task: 1

kegg_genes_subdb:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 8
  partition: debug

kegg_genes_cluster:
  time: 1000:00:00
  nodes: 1
  ntasks_per_node: 4
  partition: debug
